import React from 'react'
import ReactDOM from 'react-dom/client'
import '@fontsource-variable/inter'
import '@fontsource-variable/noto-sans-sc'
import { App } from './App'
import './typography.css'
import './styles.css'
import './layout.css'
import './calendar.css'
import './workflow.css'
import './daily-report.css'
import './production-message.css'
import './production-message-adapter.css'
import './daily-weld.css'
import './operation-sidebar.css'
import './settings-modal.css'
import './report-center.css'
import './database-viewer.css'
import './polish.css'

ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>)
