import { act } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { afterEach, expect, it, vi } from 'vitest';
const { invoke } = vi.hoisted(() => ({ invoke: vi.fn() }));
vi.mock('./bridge', () => ({ invoke }));
import { TencentWebControls } from './TencentWebControls';
(globalThis as any).IS_REACT_ACT_ENVIRONMENT = true;
let root: Root | undefined;
afterEach(() => { if (root) act(() => root!.unmount()); document.body.innerHTML = ''; });
it('owns three controls within the task, requires testing, and invalidates the proof on re-recording', async () => {
  const saved = vi.fn(async () => {}), active = vi.fn();
  invoke.mockReset().mockImplementation(async (operation: string, payload: any) => {
    if (operation === 'tencentSite.pick') return { controls: { ...payload.controls, [payload.key]: { frame: [], sampleText: '', strategies: [{}] } }, ...(payload.key === 'cellAddressBox' ? { testCell: { sheet: '26年9月', address: 'Z9' } } : {}), message: '已录制' };
    if (operation === 'tencentSite.testSheet') return { controls: payload.controls, passed: true, steps: [{ label: 'Sheet 集合', detail: '2 个标签', names: ['26年8月', '26年9月'] }], message: 'Sheet 检验通过' };
    if (operation === 'tencentSite.test') return { controls: { ...payload.controls, sheetTab: { ...payload.controls.sheetTab, sampleText: 'learned' } }, token: 'tested', steps: [{ label: '名称框定位 Y9', detail: '通过' }], message: '通过' };
    return { message: '操作完成' };
  });
  const container = document.createElement('div'); document.body.append(container); root = createRoot(container);
  await act(async () => root!.render(<TencentWebControls id="job" disabled={false} onSaved={saved} onActive={active} />));
  expect(invoke).not.toHaveBeenCalled();
  expect(container.querySelector('h2')?.textContent).toBe('网页控件录制');
  expect(container.textContent).not.toMatch(/共享|适配名称|选择网页适配/);
  const button = (text: string) => [...container.querySelectorAll('button')].find(button => button.textContent === text)!;
  await act(async () => button('录制网页控件').click());
  expect(active).toHaveBeenLastCalledWith(true);
  await act(async () => button('开始配置').click());
  expect(button('录制单元格名称框').disabled).toBe(true);
  await act(async () => button('录制 Sheet 标签').click());
  expect(invoke.mock.calls.at(-1)?.[0]).toBe('tencentSite.testSheet');
  expect(container.textContent).toContain('26年9月');
  expect(button('录制内容编辑区').disabled).toBe(true);
  await act(async () => button('录制单元格名称框').click());
  expect(container.textContent).toContain('临时测试格：26年9月!Z9');
  expect(button('检验单元格控件').disabled).toBe(true);
  await act(async () => button('录制内容编辑区').click());
  expect(button('保存网页控件').disabled).toBe(true);
  await act(async () => button('检验单元格控件').click());
  expect(button('保存网页控件').disabled).toBe(false);
  await act(async () => button('录制保存状态').click());
  expect(button('保存网页控件').disabled).toBe(true);
  expect(invoke.mock.calls.at(-1)?.[1].controls).toMatchObject({ sheetTab: {}, cellAddressBox: {}, cellEditor: {} });
  await act(async () => button('检验单元格控件').click());
  expect(invoke.mock.calls.at(-1)?.[1].controls.saveStatus).toBeDefined();
  await act(async () => button('移除保存状态').click());
  expect(button('保存网页控件').disabled).toBe(true);
  await act(async () => button('检验单元格控件').click());
  expect(invoke.mock.calls.at(-1)?.[1].controls.saveStatus).toBeUndefined();
  await act(async () => button('录制内容编辑区').click());
  expect(button('保存网页控件').disabled).toBe(true);
  await act(async () => button('检验单元格控件').click());
  await act(async () => button('保存网页控件').click());
  expect(invoke.mock.calls.find(call => call[0] === 'tencentSite.save')?.[1]).toMatchObject({ id: 'job', token: 'tested', controls: { sheetTab: { sampleText: 'learned' } } });
  expect(saved).toHaveBeenCalledOnce();
  expect(active).toHaveBeenLastCalledWith(false);
});

it('retains the independent Sheet result after cell failure, and blocks after a failed Sheet retry', async () => {
  let sheetPassed = true, cellPassed = false;
  invoke.mockReset().mockImplementation(async (operation: string, payload: any) => {
    if (operation === 'tencentSite.pick') return { controls: { ...payload.controls, [payload.key]: { frame: [], sampleText: '26年9月', strategies: [{}] } }, ...(payload.key === 'cellAddressBox' ? { testCell: { sheet: '26年9月', address: 'Z9' } } : {}), message: '已录制' };
    if (operation === 'tencentSite.captureCell') return { testCell: { sheet: '26年9月', address: 'AA20' }, message: '已读取临时测试格' };
    if (operation === 'tencentSite.testSheet') return { controls: payload.controls, passed: sheetPassed, steps: [{ label: '集合', detail: '2 个标签', names: ['26年8月', '26年9月'] }], message: sheetPassed ? 'Sheet 通过' : '选中状态未确认' };
    if (operation === 'tencentSite.test') {
      if (!cellPassed) throw Error('编辑区不可编辑');
      return { token: 'cells-passed', message: '通过' };
    }
    return { message: '完成' };
  });
  const container = document.createElement('div'); document.body.append(container); root = createRoot(container);
  await act(async () => root!.render(<TencentWebControls id="job" disabled={false} onSaved={async () => {}} onActive={() => {}} />));
  const button = (text: string) => [...container.querySelectorAll('button')].find(button => button.textContent === text)!;
  for (const label of ['录制网页控件', '开始配置', '录制 Sheet 标签', '录制单元格名称框', '录制内容编辑区', '检验单元格控件']) await act(async () => button(label).click());
  expect(container.textContent).toContain('编辑区不可编辑');
  expect(container.textContent).toContain('Sheet 检验通过');
  expect(button('保存网页控件').disabled).toBe(true);
  expect(button('检验单元格控件').disabled).toBe(false);
  cellPassed = true;
  await act(async () => button('检验单元格控件').click());
  expect(button('保存网页控件').disabled).toBe(false);
  expect(invoke.mock.calls.filter(call => call[0] === 'tencentSite.testSheet')).toHaveLength(1);
  await act(async () => button('读取当前测试格').click());
  expect(container.textContent).toContain('临时测试格：26年9月!AA20');
  expect(button('保存网页控件').disabled).toBe(true);
  expect(button('检验单元格控件').disabled).toBe(false);
  expect(invoke.mock.calls.filter(call => call[0] === 'tencentSite.pick')).toHaveLength(3);
  sheetPassed = false;
  await act(async () => button('重新检验 Sheet').click());
  expect(container.textContent).toContain('选中状态未确认');
  expect(container.textContent).toContain('26年9月');
  expect(button('保存网页控件').disabled).toBe(true);
  expect(button('检验单元格控件').disabled).toBe(true);
  expect(button('重新检验 Sheet').disabled).toBe(false);
  sheetPassed = true;
  await act(async () => button('重新检验 Sheet').click());
  expect(button('检验单元格控件').disabled).toBe(true);
  await act(async () => button('读取当前测试格').click());
  expect(button('检验单元格控件').disabled).toBe(false);
});
