import { act } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { afterEach, expect, it, vi } from 'vitest';
const { invoke } = vi.hoisted(() => ({ invoke: vi.fn() }));
vi.mock('./bridge', () => ({ invoke }));
import { TencentWebControls } from './TencentWebControls';
(globalThis as any).IS_REACT_ACT_ENVIRONMENT = true;
let root: Root | undefined;
afterEach(() => { if (root) act(() => root!.unmount()); document.body.innerHTML = ''; });
it('owns three controls within the task, requires testing, and invalidates the proof on re-recording', async () => {
  const saved = vi.fn(async () => {}), active = vi.fn();
  invoke.mockReset().mockImplementation(async (operation: string, payload: any) => {
    if (operation === 'tencentSite.pick') return { controls: { ...payload.controls, [payload.key]: { frame: [], sampleText: '', strategies: [{}] } }, message: '已录制' };
    if (operation === 'tencentSite.test') return { controls: { ...payload.controls, sheetTab: { ...payload.controls.sheetTab, sampleText: 'learned' } }, token: 'tested', steps: [{ label: '名称框定位 J9', detail: '通过' }], message: '通过' };
    return { message: '操作完成' };
  });
  const container = document.createElement('div'); document.body.append(container); root = createRoot(container);
  await act(async () => root!.render(<TencentWebControls id="job" disabled={false} onSaved={saved} onActive={active} />));
  expect(invoke).not.toHaveBeenCalled();
  expect(container.querySelector('legend')?.textContent).toBe('网页控件');
  expect(container.textContent).not.toMatch(/共享|适配名称|选择网页适配/);
  const button = (text: string) => [...container.querySelectorAll('button')].find(button => button.textContent === text)!;
  await act(async () => button('录制网页控件').click());
  expect(active).toHaveBeenLastCalledWith(true);
  await act(async () => button('开始配置').click());
  await act(async () => button('录制 Sheet 标签').click());
  await act(async () => button('录制单元格名称框').click());
  expect(button('测试网页控件').disabled).toBe(true);
  await act(async () => button('录制内容编辑区').click());
  expect(button('保存网页控件').disabled).toBe(true);
  await act(async () => button('测试网页控件').click());
  expect(button('保存网页控件').disabled).toBe(false);
  await act(async () => button('录制内容编辑区').click());
  expect(button('保存网页控件').disabled).toBe(true);
  await act(async () => button('测试网页控件').click());
  await act(async () => button('保存网页控件').click());
  expect(invoke.mock.calls.find(call => call[0] === 'tencentSite.save')?.[1]).toMatchObject({ id: 'job', token: 'tested', controls: { sheetTab: { sampleText: 'learned' } } });
  expect(saved).toHaveBeenCalledOnce();
  expect(active).toHaveBeenLastCalledWith(false);
});
