import { act } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { afterEach, expect, it, vi } from 'vitest';
const { invoke } = vi.hoisted(() => ({ invoke: vi.fn() }));
vi.mock('./bridge', () => ({ invoke }));
import { TencentSiteProfiles } from './TencentSiteProfiles';
(globalThis as any).IS_REACT_ACT_ENVIRONMENT = true;
let root: Root | undefined;
afterEach(() => { if (root) act(() => root!.unmount()); document.body.innerHTML = ''; });
it('records two controls, gates save on test, invalidates test on edit, and selects the saved shared profile', async () => {
  const changed = vi.fn(), active = vi.fn();
  invoke.mockReset().mockImplementation(async (operation: string, payload: any) => {
    if (operation === 'tencentSite.list') return { profiles: [] };
    if (operation === 'tencentSite.pick') return { profile: { ...payload.profile, controls: { ...payload.profile.controls, [payload.key]: { frame: [], sampleText: '', strategies: [{}] } } }, message: '已录制' };
    if (operation === 'tencentSite.test') return { token: 'tested', steps: [{ label: '名称框定位 J9', detail: '通过' }], message: '通过' };
    if (operation === 'tencentSite.save') return { profile: { ...payload.profile, id: 'saved' }, message: '保存成功' };
    return { message: '已打开' };
  });
  const container = document.createElement('div'); document.body.append(container); root = createRoot(container);
  await act(async () => root!.render(<TencentSiteProfiles value="" documentUrl="https://docs.qq.com/sheet/test" disabled={false} onChange={changed} onActive={active} />));
  expect(invoke.mock.calls.map(call => call[0])).toEqual(['tencentSite.list']);
  const button = (text: string) => [...container.querySelectorAll('button')].find(button => button.textContent === text)!;
  await act(async () => button('新建腾讯文档适配').click());
  expect(active).toHaveBeenLastCalledWith(true);
  expect(button('保存适配配置').disabled).toBe(true);
  await act(async () => button('开始配置').click());
  await act(async () => button('录制 Sheet 标签').click());
  await act(async () => button('录制单元格名称框').click());
  expect(button('保存适配配置').disabled).toBe(true);
  await act(async () => button('测试适配').click());
  expect(button('保存适配配置').disabled).toBe(false);
  const name = container.querySelector<HTMLInputElement>('input[maxlength="80"]')!;
  await act(async () => { Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value')!.set!.call(name, '另一适配'); name.dispatchEvent(new Event('input', { bubbles: true })); });
  expect(button('保存适配配置').disabled).toBe(true);
  await act(async () => button('测试适配').click());
  await act(async () => button('保存适配配置').click());
  expect(invoke.mock.calls.find(call => call[0] === 'tencentSite.save')?.[1]).toMatchObject({ token: 'tested' });
  expect(changed).toHaveBeenLastCalledWith('saved');
  expect(active).toHaveBeenLastCalledWith(false);
});
