<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <RootNamespace>ProductionAssistant</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ProductionAssistant.Core\ProductionAssistant.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.1" />
  </ItemGroup>
</Project>
